👔 Do not start a trip if we see a beacon in non-fleet mode
Before this change, if we saw a beacon while in `WAITING_FOR_TRIP_START` state,
we would generate a `TripStarted` transition _regardless_ of whether it was a
fleet deployment or not. However, in fleet mode, we didn't actually start
fine-grained tracking. And when we received the geofence exit, we ignored it
because we were already in ONGOING_TRIP, so we didn't start fine-grained tracking.

This had two implications:
- we ended up with "straight-line" trips, because we didn't start fine-grained
  tracking, AND
- we would not show unpushed draft trips because the transition matching code
  expects to see an EXITED_GEOFENCE that it can match up with the end transitions

Testing done:

- Fleet configuration

```
In TripDiaryStateMachine, received transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START
DEBUG: In TripDiaryStateMachine, received transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START
data has 101 bytes, str has size 101
data has 69 bytes, str has size 69
ERROR: Got transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START without fleet mode
DEBUG: ERROR: Got transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START without fleet mode
Ignoring silent push notification
DEBUG:parseState: state = STATE_WAITING_FOR_TRIP_START;
      platformId = ios
```

- non-fleet configuration

```
In TripDiaryStateMachine, received transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START
DEBUG: In TripDiaryStateMachine, received transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START
data has 101 bytes, str has size 101
data has 67 bytes, str has size 67
Got transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START with fleet mode, starting location tracking
DEBUG: Got transition T_BLE_BEACON_FOUND in state STATE_WAITING_FOR_TRIP_START with fleet mode, starting location tracking
started fine location tracking with accuracy = -1 and distanceFilter = 1
DEBUG: started fine location tracking with accuracy = -1 and distanceFilter = 1
In TripDiaryStateMachine, received transition T_TRIP_STARTED in state STATE_WAITING_FOR_TRIP_START
DEBUG: In TripDiaryStateMachine, received transition T_TRIP_STARTED in state STATE_WAITING_FOR_TRIP_START
data has 97 bytes, str has size 97
data has 69 bytes, str has size 69
Moved from STATE_WAITING_FOR_TRIP_START to STATE_ONGOING_TRIP
DEBUG: Moved from STATE_WAITING_FOR_TRIP_START to STATE_ONGOING_TRIP
```